version: "3.9"

networks:
  mongodb-network:
    driver: bridge

services:
  mongo:
    container_name: mongodb-container
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./volumes/mongodb:/data/db
      - ./volumes/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    networks:
      - mongodb-network
    restart: always

  mongo-express:
    container_name: mongoexpress-container
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://user:password@mongodb-container:27017/
    networks:
      - mongodb-network
    restart: always
     