version: "3.9"

networks:
  mongodb-network:
    driver: bridge

services:
  mongo:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./volumes/mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      - mongodb-network
    restart: unless-stopped

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - mongodb-network
    restart: unless-stopped
    depends_on:
      - mongo
     