server:
  port: 8080

spring:
  application:
    name: webflux-course
  data:
    mongodb:
      uri: mongodb://${DB_USER:admin}:${DB_PASSWORD:pass}@localhost:27017/${DB_NAME:WebfluxCourse}
      auto-index-creation: true